# coding: utf-8

"""
    HR API

    <a href='swaggerv2.json'>Download Swagger Json in OAS2 Format.</a>

    The version of the OpenAPI document: 2
    Contact: hrapi@iris.co.uk
    Created by: https://help.iris.co.uk/hr/cascade/api/
"""

from datetime import datetime, date
import typing
from enum import Enum
from typing_extensions import TypedDict, Literal, TYPE_CHECKING


class RequiredAbsenceReasonModel(TypedDict):
    pass

class OptionalAbsenceReasonModel(TypedDict, total=False):
    # The Parent ID of this Absence Reason. <br />  Cascade Source: [ValidAttendanceTypes].[Key].
    ParentId: typing.Optional[str]

    # The Name of this Absence Reason. <br />  Cascade Source: <br />  [ValidAttendanceCategory].[Category] when ParentID is null; <br />  [ValidAttendanceTypes].[Type] when ParentID is not null.
    Name: typing.Optional[str]

    # This Absence Reason represents a Holiday. <br />  Cascade Source: [ValidAttendanceCategory].[Holiday]
    Holiday: typing.Optional[bool]

    # This Absence Reason represents an Absence. <br />  Cascade Source: [ValidAttendanceCategory].[Absent]
    Absent: typing.Optional[bool]

    # This Absence Reason represents a Sickness. <br />  Cascade Source: [ValidAttendanceCategory].[Sick]
    Sick: typing.Optional[bool]

    # This Absence Reason has Statutory Maternity Pay. <br />  Cascade Source: [ValidAttendanceCategory].[SMPApplicable]
    StatutoryMaternityPayApplicable: typing.Optional[bool]

    # This Absence Reason represents an absence for Study or Exam. <br />  Cascade Source: [ValidAttendanceCategory].[Code] = 96 or 97
    StudyExam: typing.Optional[bool]

    # This Absence Reason represents Flexi Leave. <br />  Cascade Source: [ValidAttendanceCategory].[Code] = 11
    FlexiLeave: typing.Optional[bool]

    # The ID of the Absence Reason. <br />  This field is generated by Iris HR platform and not related to the Cascade ID.
    Id: typing.Optional[str]

    # The date time when the Absence Reason was created in the Iris HR platform.
    CreatedOn: datetime

    # Not used as the Iris HR platform has no concept of users at the moment.
    CreatedBy: typing.Optional[str]

    # The date time when the Absence Reason was created or last updated.
    LastModifiedOn: typing.Optional[datetime]

    # Not used as the Iris HR platform has no concept of users at the moment.
    LastModifiedBy: typing.Optional[str]

class AbsenceReasonModel(RequiredAbsenceReasonModel, OptionalAbsenceReasonModel):
    pass
