# coding: utf-8

"""
    HR API

    <a href='swaggerv2.json'>Download Swagger Json in OAS2 Format.</a>

    The version of the OpenAPI document: 2
    Contact: hrapi@iris.co.uk
    Created by: https://help.iris.co.uk/hr/cascade/api/
"""

from datetime import datetime, date
import typing
from enum import Enum
from typing_extensions import TypedDict, Literal, TYPE_CHECKING

from iris_software_group_cascade_python_sdk.type.bank_address import BankAddress

class RequiredBankDetailsModel(TypedDict):
    pass

class OptionalBankDetailsModel(TypedDict, total=False):
    # The ID of the HR Employee. <br />  Must exist in the Employee Service.
    EmployeeId: typing.Optional[str]

    # Bank Name. <br />  Cascade Source: [EmployeeBank].[BankName]
    BankName: typing.Optional[str]

    BankAddress: BankAddress

    # Account Name. <br />  Cascade Source: [EmployeeBank].[AccountName]
    AccountName: typing.Optional[str]

    # Account Number. <br />  Cascade Source: [EmployeeBank].[AccountNumber]
    AccountNumber: typing.Optional[str]

    # Sort Code. <br />  Cascade Source: [EmployeeBank].[SortCode]
    SortCode: typing.Optional[str]

    # Roll Number. <br />  Cascade Source: [EmployeeBank].[RollNumber]
    RollNumber: typing.Optional[str]

    # The Internal ID for the source HR Product. <br />  Cascade Source: [EmployeeBank].[RUID]
    SourceSystemId: typing.Optional[str]

    # The date when the Bank details record was created in the Source HR System. <br />  Cascade Source: [EmployeeBank].[SYS_EffectiveDate]
    SourceSystemCreatedOn: typing.Optional[datetime]

    # The latest date when the Bank details record was created or last updated in the Source HR System. <br />  Cascade Source: Latest of [EmployeeBank].[SYS_ModifiedDate]
    SourceSystemLastModifiedOn: typing.Optional[datetime]

    # The ID of Bank Details. <br />  This field is generated by Iris HR platform and not related to the Cascade ID.
    Id: typing.Optional[str]

    # The date time when the Bank Details was created in the Iris HR platform.
    CreatedOn: datetime

    # Not used as the Iris HR platform has no concept of users at the moment.
    CreatedBy: typing.Optional[str]

    # The date time when the Bank Details was created or last updated.
    LastModifiedOn: typing.Optional[datetime]

    # Not used as the Iris HR platform has no concept of users at the moment.
    LastModifiedBy: typing.Optional[str]

class BankDetailsModel(RequiredBankDetailsModel, OptionalBankDetailsModel):
    pass
