# coding: utf-8

"""
    HR API

    <a href='swaggerv2.json'>Download Swagger Json in OAS2 Format.</a>

    The version of the OpenAPI document: 2
    Contact: hrapi@iris.co.uk
    Created by: https://help.iris.co.uk/hr/cascade/api/
"""

from datetime import datetime, date
import typing
from enum import Enum
from typing_extensions import TypedDict, Literal, TYPE_CHECKING


class RequiredBenefitModel(TypedDict):
    pass

class OptionalBenefitModel(TypedDict, total=False):
    # The EmployeeId. <br />  Cascade Source: [EmployeeBenefits].[EmployeeId]
    EmployeeId: typing.Optional[str]

    # The Type. <br />  Cascade Source: [EmployeeBenefits].[Code]
    Type: typing.Optional[str]

    # The Description. <br />  Cascade Source: [EmployeeBenefits].[Notes]
    Description: typing.Optional[str]

    # The Value. <br />  Cascade Source: [EmployeeBenefits].[Value]
    Value: typing.Optional[typing.Union[int, float]]

    # The Start Date. <br />  Cascade Source: [EmployeeBenefits].[StartDate]
    StartDate: typing.Optional[datetime]

    # The End Date. <br />  Cascade Source: [EmployeeBenefits].[EndDate]
    EndDate: typing.Optional[datetime]

    # The P11DValue. <br />  Cascade Source: [EmployeeBenefits].[P11DValueCurrency]
    P11DValue: typing.Optional[typing.Union[int, float]]

    # The Suspended value. <br />  Cascade Source: [EmployeeBenefits].[Suspended]
    Suspended: bool

    # The ID of the Benefit. <br />  This field is generated by Iris HR platform and not related to the Cascade ID.
    Id: typing.Optional[str]

    # Source HR System Id. <br />  Cascade Source: [EmployeeBenefits].[Ruid] <br />  Read Only
    SourceSystemId: typing.Optional[str]

    # The date time when the Benefit was created in the Iris HR platform.
    CreatedOn: datetime

    # Not used as the Iris HR platform has no concept of users at the moment.
    CreatedBy: typing.Optional[str]

    # Not used as the Iris HR platform has no concept of users at the moment.
    LastModifiedOn: typing.Optional[datetime]

    # Not used as the Iris HR platform has no concept of users at the moment.
    LastModifiedBy: typing.Optional[str]

class BenefitModel(RequiredBenefitModel, OptionalBenefitModel):
    pass
