# coding: utf-8

"""
    HR API

    <a href='swaggerv2.json'>Download Swagger Json in OAS2 Format.</a>

    The version of the OpenAPI document: 2
    Contact: hrapi@iris.co.uk
    Created by: https://help.iris.co.uk/hr/cascade/api/
"""

from datetime import datetime, date
import typing
from enum import Enum
from typing_extensions import TypedDict, Literal, TYPE_CHECKING


class RequiredHierarchyNodeModel(TypedDict):
    pass

class OptionalHierarchyNodeModel(TypedDict, total=False):
    # The Parent ID of this Hierarchy node. <br />  Must exist in the Hierarchy Service.
    ParentId: typing.Optional[str]

    # The Level of the Hierarchy node. <br />  Cascade Source: [ValidHierarchyX].[level]
    Level: int

    # The Title of this Hierarchy node. <br />  Cascade Source: [ValidHierarchyX].[name]
    Title: typing.Optional[str]

    # Hierarchy node is disabled. <br />  Cascade Source: [ValidHierarchyX].[disabled]
    Disabled: bool

    # Source HR System Id. <br />  Cascade Source: [ValidHierarchyX].[HierarchyNode] <br />  Read Only
    SourceSystemId: typing.Optional[str]

    # The date when the Hierarchy node record was created in the Source HR System. <br />  Cascade Source: [ValidHierarchyX].[createdon]
    SourceSystemCreatedOn: typing.Optional[datetime]

    # The date when the Hierarchy node record was created or last updated in the Source HR System. <br />  Cascade Source: [ValidHierarchyX].[disabledon] if exists else [ValidHierachyX].[createdon]
    SourceSystemLastModifiedOn: typing.Optional[datetime]

    # This ID of the Hierarchy node. <br />  This field is generated by Iris HR platform and not related to the Cascade ID.
    Id: typing.Optional[str]

    # The date time when the Hierarchy node was created in the Iris HR platform.
    CreatedOn: datetime

    # Not used as the Iris HR platform has no concept of users at the moment.
    CreatedBy: typing.Optional[str]

    # The date time when the Hierarchy node was created or last updated.
    LastModifiedOn: typing.Optional[datetime]

    # Not used as the Iris HR platform has no concept of users at the moment.
    LastModifiedBy: typing.Optional[str]

class HierarchyNodeModel(RequiredHierarchyNodeModel, OptionalHierarchyNodeModel):
    pass
