# coding: utf-8

"""
    HR API

    <a href='swaggerv2.json'>Download Swagger Json in OAS2 Format.</a>

    The version of the OpenAPI document: 2
    Contact: hrapi@iris.co.uk
    Created by: https://help.iris.co.uk/hr/cascade/api/
"""

from datetime import datetime, date
import typing
from enum import Enum
from typing_extensions import TypedDict, Literal, TYPE_CHECKING

from iris_software_group_cascade_python_sdk.type.public_holiday_day import PublicHolidayDay

class RequiredPublicHolidayModel(TypedDict):
    pass

class OptionalPublicHolidayModel(TypedDict, total=False):
    # The description of the Public Holiday. <br />  This is usually the location of the Public Holiday. <br />  Cascade Source: [ValidBankHolidays].[HolidayLocation]
    Description: typing.Optional[str]

    # A list of Public Holiday Days.
    Days: typing.Optional[typing.List[PublicHolidayDay]]

    # This ID is generated by the Iris Hr platform and does not relate to the Cascade ID.
    Id: typing.Optional[str]

    # The date when the Public Holiday was created in the Iris HR platform.
    CreatedOn: datetime

    # Not used as the Iris HR platform has no concept of users.
    CreatedBy: typing.Optional[str]

    # The date when the Public Holiday was created or last updated.
    LastModifiedOn: typing.Optional[datetime]

    # Not used as the Iris HR platform has no concept of users.
    LastModifiedBy: typing.Optional[str]

class PublicHolidayModel(RequiredPublicHolidayModel, OptionalPublicHolidayModel):
    pass
