# coding: utf-8

"""
    HR API

    <a href='swaggerv2.json'>Download Swagger Json in OAS2 Format.</a>

    The version of the OpenAPI document: 2
    Contact: hrapi@iris.co.uk
    Created by: https://help.iris.co.uk/hr/cascade/api/
"""

from datetime import datetime, date
import typing
from enum import Enum
from typing_extensions import TypedDict, Literal, TYPE_CHECKING
from pydantic import BaseModel, Field, RootModel, ConfigDict


class AbsenceReasonModel(BaseModel):
    # The Parent ID of this Absence Reason. <br />  Cascade Source: [ValidAttendanceTypes].[Key].
    parent_id: typing.Optional[typing.Optional[str]] = Field(None, alias='ParentId')

    # The Name of this Absence Reason. <br />  Cascade Source: <br />  [ValidAttendanceCategory].[Category] when ParentID is null; <br />  [ValidAttendanceTypes].[Type] when ParentID is not null.
    name: typing.Optional[typing.Optional[str]] = Field(None, alias='Name')

    # This Absence Reason represents a Holiday. <br />  Cascade Source: [ValidAttendanceCategory].[Holiday]
    holiday: typing.Optional[typing.Optional[bool]] = Field(None, alias='Holiday')

    # This Absence Reason represents an Absence. <br />  Cascade Source: [ValidAttendanceCategory].[Absent]
    absent: typing.Optional[typing.Optional[bool]] = Field(None, alias='Absent')

    # This Absence Reason represents a Sickness. <br />  Cascade Source: [ValidAttendanceCategory].[Sick]
    sick: typing.Optional[typing.Optional[bool]] = Field(None, alias='Sick')

    # This Absence Reason has Statutory Maternity Pay. <br />  Cascade Source: [ValidAttendanceCategory].[SMPApplicable]
    statutory_maternity_pay_applicable: typing.Optional[typing.Optional[bool]] = Field(None, alias='StatutoryMaternityPayApplicable')

    # This Absence Reason represents an absence for Study or Exam. <br />  Cascade Source: [ValidAttendanceCategory].[Code] = 96 or 97
    study_exam: typing.Optional[typing.Optional[bool]] = Field(None, alias='StudyExam')

    # This Absence Reason represents Flexi Leave. <br />  Cascade Source: [ValidAttendanceCategory].[Code] = 11
    flexi_leave: typing.Optional[typing.Optional[bool]] = Field(None, alias='FlexiLeave')

    # The ID of the Absence Reason. <br />  This field is generated by Iris HR platform and not related to the Cascade ID.
    id: typing.Optional[typing.Optional[str]] = Field(None, alias='Id')

    # The date time when the Absence Reason was created in the Iris HR platform.
    created_on: typing.Optional[datetime] = Field(None, alias='CreatedOn')

    # Not used as the Iris HR platform has no concept of users at the moment.
    created_by: typing.Optional[typing.Optional[str]] = Field(None, alias='CreatedBy')

    # The date time when the Absence Reason was created or last updated.
    last_modified_on: typing.Optional[typing.Optional[datetime]] = Field(None, alias='LastModifiedOn')

    # Not used as the Iris HR platform has no concept of users at the moment.
    last_modified_by: typing.Optional[typing.Optional[str]] = Field(None, alias='LastModifiedBy')

    model_config = ConfigDict(
        protected_namespaces=(),
        arbitrary_types_allowed=True
    )
