# coding: utf-8

"""
    HR API

    <a href='swaggerv2.json'>Download Swagger Json in OAS2 Format.</a>

    The version of the OpenAPI document: 2
    Contact: hrapi@iris.co.uk
    Created by: https://help.iris.co.uk/hr/cascade/api/
"""

from datetime import datetime, date
import typing
from enum import Enum
from typing_extensions import TypedDict, Literal, TYPE_CHECKING
from pydantic import BaseModel, Field, RootModel, ConfigDict


class BenefitModel(BaseModel):
    # The EmployeeId. <br />  Cascade Source: [EmployeeBenefits].[EmployeeId]
    employee_id: typing.Optional[typing.Optional[str]] = Field(None, alias='EmployeeId')

    # The Type. <br />  Cascade Source: [EmployeeBenefits].[Code]
    type: typing.Optional[typing.Optional[str]] = Field(None, alias='Type')

    # The Description. <br />  Cascade Source: [EmployeeBenefits].[Notes]
    description: typing.Optional[typing.Optional[str]] = Field(None, alias='Description')

    # The Value. <br />  Cascade Source: [EmployeeBenefits].[Value]
    value: typing.Optional[typing.Optional[typing.Union[int, float]]] = Field(None, alias='Value')

    # The Start Date. <br />  Cascade Source: [EmployeeBenefits].[StartDate]
    start_date: typing.Optional[typing.Optional[datetime]] = Field(None, alias='StartDate')

    # The End Date. <br />  Cascade Source: [EmployeeBenefits].[EndDate]
    end_date: typing.Optional[typing.Optional[datetime]] = Field(None, alias='EndDate')

    # The P11DValue. <br />  Cascade Source: [EmployeeBenefits].[P11DValueCurrency]
    p11_d_value: typing.Optional[typing.Optional[typing.Union[int, float]]] = Field(None, alias='P11DValue')

    # The Suspended value. <br />  Cascade Source: [EmployeeBenefits].[Suspended]
    suspended: typing.Optional[bool] = Field(None, alias='Suspended')

    # The ID of the Benefit. <br />  This field is generated by Iris HR platform and not related to the Cascade ID.
    id: typing.Optional[typing.Optional[str]] = Field(None, alias='Id')

    # Source HR System Id. <br />  Cascade Source: [EmployeeBenefits].[Ruid] <br />  Read Only
    source_system_id: typing.Optional[typing.Optional[str]] = Field(None, alias='SourceSystemId')

    # The date time when the Benefit was created in the Iris HR platform.
    created_on: typing.Optional[datetime] = Field(None, alias='CreatedOn')

    # Not used as the Iris HR platform has no concept of users at the moment.
    created_by: typing.Optional[typing.Optional[str]] = Field(None, alias='CreatedBy')

    # Not used as the Iris HR platform has no concept of users at the moment.
    last_modified_on: typing.Optional[typing.Optional[datetime]] = Field(None, alias='LastModifiedOn')

    # Not used as the Iris HR platform has no concept of users at the moment.
    last_modified_by: typing.Optional[typing.Optional[str]] = Field(None, alias='LastModifiedBy')

    model_config = ConfigDict(
        protected_namespaces=(),
        arbitrary_types_allowed=True
    )
