# coding: utf-8

"""
    HR API

    <a href='swaggerv2.json'>Download Swagger Json in OAS2 Format.</a>

    The version of the OpenAPI document: 2
    Contact: hrapi@iris.co.uk
    Created by: https://help.iris.co.uk/hr/cascade/api/
"""

from datetime import datetime, date
import typing
from enum import Enum
from typing_extensions import TypedDict, Literal, TYPE_CHECKING
from pydantic import BaseModel, Field, RootModel, ConfigDict

from iris_software_group_cascade_python_sdk.pydantic.public_holiday_day import PublicHolidayDay

class PublicHolidayModel(BaseModel):
    # The description of the Public Holiday. <br />  This is usually the location of the Public Holiday. <br />  Cascade Source: [ValidBankHolidays].[HolidayLocation]
    description: typing.Optional[typing.Optional[str]] = Field(None, alias='Description')

    # A list of Public Holiday Days.
    days: typing.Optional[typing.Optional[typing.List[PublicHolidayDay]]] = Field(None, alias='Days')

    # This ID is generated by the Iris Hr platform and does not relate to the Cascade ID.
    id: typing.Optional[typing.Optional[str]] = Field(None, alias='Id')

    # The date when the Public Holiday was created in the Iris HR platform.
    created_on: typing.Optional[datetime] = Field(None, alias='CreatedOn')

    # Not used as the Iris HR platform has no concept of users.
    created_by: typing.Optional[typing.Optional[str]] = Field(None, alias='CreatedBy')

    # The date when the Public Holiday was created or last updated.
    last_modified_on: typing.Optional[typing.Optional[datetime]] = Field(None, alias='LastModifiedOn')

    # Not used as the Iris HR platform has no concept of users.
    last_modified_by: typing.Optional[typing.Optional[str]] = Field(None, alias='LastModifiedBy')

    model_config = ConfigDict(
        protected_namespaces=(),
        arbitrary_types_allowed=True
    )
