# coding: utf-8

"""
    HR API

    <a href='swaggerv2.json'>Download Swagger Json in OAS2 Format.</a>

    The version of the OpenAPI document: 2
    Contact: hrapi@iris.co.uk
    Created by: https://help.iris.co.uk/hr/cascade/api/
"""

from datetime import date, datetime  # noqa: F401
import decimal  # noqa: F401
import functools  # noqa: F401
import io  # noqa: F401
import re  # noqa: F401
import typing  # noqa: F401
import typing_extensions  # noqa: F401
import uuid  # noqa: F401

import frozendict  # noqa: F401

from iris_software_group_cascade_python_sdk import schemas  # noqa: F401


class PhoneType(
    schemas.EnumBase,
    schemas.StrSchema
):
    """
    This class is auto generated by Konfig (https://konfigthis.com)

    The Type of Phone
    """


    class MetaOapg:
        enum_value_to_name = {
            "Mobile": "MOBILE",
            "Landline": "LANDLINE",
        }
    
    @schemas.classproperty
    def MOBILE(cls):
        return cls("Mobile")
    
    @schemas.classproperty
    def LANDLINE(cls):
        return cls("Landline")
