# coding: utf-8

# flake8: noqa

# import all models into this package
# if you have many models here with many references from one model to another this may
# raise a RecursionError
# to avoid this, import only the models that you directly need like:
# from from iris_software_group_cascade_python_sdk.model.pet import Pet
# or import this package, but before doing it, use:
# import sys
# sys.setrecursionlimit(n)

from iris_software_group_cascade_python_sdk.model.absence_day_model import AbsenceDayModel
from iris_software_group_cascade_python_sdk.model.absence_day_query_model import AbsenceDayQueryModel
from iris_software_group_cascade_python_sdk.model.absence_days_create_absence_day200_response import AbsenceDaysCreateAbsenceDay200Response
from iris_software_group_cascade_python_sdk.model.absence_days_create_absence_day_response import AbsenceDaysCreateAbsenceDayResponse
from iris_software_group_cascade_python_sdk.model.absence_model import AbsenceModel
from iris_software_group_cascade_python_sdk.model.absence_query_model import AbsenceQueryModel
from iris_software_group_cascade_python_sdk.model.absence_query_model_value import AbsenceQueryModelValue
from iris_software_group_cascade_python_sdk.model.absence_query_model_value_item import AbsenceQueryModelValueItem
from iris_software_group_cascade_python_sdk.model.absence_reason_model import AbsenceReasonModel
from iris_software_group_cascade_python_sdk.model.absence_reason_query_model import AbsenceReasonQueryModel
from iris_software_group_cascade_python_sdk.model.absences_create_new_absence200_response import AbsencesCreateNewAbsence200Response
from iris_software_group_cascade_python_sdk.model.absences_create_new_absence_response import AbsencesCreateNewAbsenceResponse
from iris_software_group_cascade_python_sdk.model.address import Address
from iris_software_group_cascade_python_sdk.model.bank_address import BankAddress
from iris_software_group_cascade_python_sdk.model.bank_details_create_bank_detail200_response import BankDetailsCreateBankDetail200Response
from iris_software_group_cascade_python_sdk.model.bank_details_create_bank_detail_response import BankDetailsCreateBankDetailResponse
from iris_software_group_cascade_python_sdk.model.bank_details_model import BankDetailsModel
from iris_software_group_cascade_python_sdk.model.bank_details_query_model import BankDetailsQueryModel
from iris_software_group_cascade_python_sdk.model.benefit_model import BenefitModel
from iris_software_group_cascade_python_sdk.model.benefit_query_model import BenefitQueryModel
from iris_software_group_cascade_python_sdk.model.create_absence_command import CreateAbsenceCommand
from iris_software_group_cascade_python_sdk.model.create_absence_day_command import CreateAbsenceDayCommand
from iris_software_group_cascade_python_sdk.model.create_bank_details_command import CreateBankDetailsCommand
from iris_software_group_cascade_python_sdk.model.create_employee_command import CreateEmployeeCommand
from iris_software_group_cascade_python_sdk.model.create_job_command import CreateJobCommand
from iris_software_group_cascade_python_sdk.model.day_part import DayPart
from iris_software_group_cascade_python_sdk.model.email import Email
from iris_software_group_cascade_python_sdk.model.employee_absence_reason_model import EmployeeAbsenceReasonModel
from iris_software_group_cascade_python_sdk.model.employee_model import EmployeeModel
from iris_software_group_cascade_python_sdk.model.employee_query_model import EmployeeQueryModel
from iris_software_group_cascade_python_sdk.model.employees_create_new_employee200_response import EmployeesCreateNewEmployee200Response
from iris_software_group_cascade_python_sdk.model.employees_create_new_employee_response import EmployeesCreateNewEmployeeResponse
from iris_software_group_cascade_python_sdk.model.entitlement_model import EntitlementModel
from iris_software_group_cascade_python_sdk.model.entitlement_query_model import EntitlementQueryModel
from iris_software_group_cascade_python_sdk.model.hierarchy_node_model import HierarchyNodeModel
from iris_software_group_cascade_python_sdk.model.hierarchy_node_query_model import HierarchyNodeQueryModel
from iris_software_group_cascade_python_sdk.model.job_model import JobModel
from iris_software_group_cascade_python_sdk.model.job_query_model import JobQueryModel
from iris_software_group_cascade_python_sdk.model.jobs_create_new_job200_response import JobsCreateNewJob200Response
from iris_software_group_cascade_python_sdk.model.jobs_create_new_job_response import JobsCreateNewJobResponse
from iris_software_group_cascade_python_sdk.model.jobs_get_by_id200_response import JobsGetById200Response
from iris_software_group_cascade_python_sdk.model.jobs_get_by_id_response import JobsGetByIdResponse
from iris_software_group_cascade_python_sdk.model.ownership import Ownership
from iris_software_group_cascade_python_sdk.model.phone import Phone
from iris_software_group_cascade_python_sdk.model.phone_type import PhoneType
from iris_software_group_cascade_python_sdk.model.problem_details import ProblemDetails
from iris_software_group_cascade_python_sdk.model.public_holiday_day import PublicHolidayDay
from iris_software_group_cascade_python_sdk.model.public_holiday_model import PublicHolidayModel
from iris_software_group_cascade_python_sdk.model.public_holiday_query_model import PublicHolidayQueryModel
from iris_software_group_cascade_python_sdk.model.update_absence_command import UpdateAbsenceCommand
from iris_software_group_cascade_python_sdk.model.update_absence_day_command import UpdateAbsenceDayCommand
from iris_software_group_cascade_python_sdk.model.update_bank_details_command import UpdateBankDetailsCommand
from iris_software_group_cascade_python_sdk.model.update_employee_command import UpdateEmployeeCommand
from iris_software_group_cascade_python_sdk.model.update_job_command import UpdateJobCommand
