# coding: utf-8

"""
    HR API

    <a href='swaggerv2.json'>Download Swagger Json in OAS2 Format.</a>

    The version of the OpenAPI document: 2
    Contact: hrapi@iris.co.uk
    Created by: https://help.iris.co.uk/hr/cascade/api/
"""

from iris_software_group_cascade_python_sdk.paths.attendance_absencedays.post import CreateAbsenceDay
from iris_software_group_cascade_python_sdk.paths.attendance_absencedays_id.delete import DeleteById
from iris_software_group_cascade_python_sdk.paths.attendance_absencedays_id.get import GetById
from iris_software_group_cascade_python_sdk.paths.attendance_absencedays.get import GetList
from iris_software_group_cascade_python_sdk.paths.attendance_absencedays_id.put import UpdateAbsenceDay
from iris_software_group_cascade_python_sdk.apis.tags.absence_days_api_raw import AbsenceDaysApiRaw


class AbsenceDaysApi(
    CreateAbsenceDay,
    DeleteById,
    GetById,
    GetList,
    UpdateAbsenceDay,
):
    """NOTE:
    This class is auto generated by Konfig (https://konfigthis.com)
    """
    raw: AbsenceDaysApiRaw

    def __init__(self, api_client=None):
        super().__init__(api_client)
        self.raw = AbsenceDaysApiRaw(api_client)
