# coding: utf-8

"""
    HR API

    <a href='swaggerv2.json'>Download Swagger Json in OAS2 Format.</a>

    The version of the OpenAPI document: 2
    Contact: hrapi@iris.co.uk
    Created by: https://help.iris.co.uk/hr/cascade/api/
"""

from iris_software_group_cascade_python_sdk.paths.attendance_absencereasons_id.get import GetById
from iris_software_group_cascade_python_sdk.paths.attendance_absencereasons_id_employees_employee_id.get import GetEmployeeById
from iris_software_group_cascade_python_sdk.paths.attendance_absencereasons.get import List
from iris_software_group_cascade_python_sdk.apis.tags.absence_reasons_api_raw import AbsenceReasonsApiRaw


class AbsenceReasonsApi(
    GetById,
    GetEmployeeById,
    List,
):
    """NOTE:
    This class is auto generated by Konfig (https://konfigthis.com)
    """
    raw: AbsenceReasonsApiRaw

    def __init__(self, api_client=None):
        super().__init__(api_client)
        self.raw = AbsenceReasonsApiRaw(api_client)
