# coding: utf-8

"""
    HR API

    <a href='swaggerv2.json'>Download Swagger Json in OAS2 Format.</a>

    The version of the OpenAPI document: 2
    Contact: hrapi@iris.co.uk
    Created by: https://help.iris.co.uk/hr/cascade/api/
"""

from iris_software_group_cascade_python_sdk.paths.employees.post import CreateNewEmployee
from iris_software_group_cascade_python_sdk.paths.employees_id.get import GetById
from iris_software_group_cascade_python_sdk.paths.employees.get import GetList
from iris_software_group_cascade_python_sdk.paths.employees_id.put import UpdateById
from iris_software_group_cascade_python_sdk.apis.tags.employees_api_raw import EmployeesApiRaw


class EmployeesApi(
    CreateNewEmployee,
    GetById,
    GetList,
    UpdateById,
):
    """NOTE:
    This class is auto generated by Konfig (https://konfigthis.com)
    """
    raw: EmployeesApiRaw

    def __init__(self, api_client=None):
        super().__init__(api_client)
        self.raw = EmployeesApiRaw(api_client)
