# coding: utf-8

"""
    HR API

    <a href='swaggerv2.json'>Download Swagger Json in OAS2 Format.</a>

    The version of the OpenAPI document: 2
    Contact: hrapi@iris.co.uk
    Created by: https://help.iris.co.uk/hr/cascade/api/
"""

from iris_software_group_cascade_python_sdk.paths.hierarchy.get import GetList
from iris_software_group_cascade_python_sdk.paths.hierarchy_id.get import GetNodeById
from iris_software_group_cascade_python_sdk.paths.hierarchy_id_path.get import GetPathById
from iris_software_group_cascade_python_sdk.apis.tags.hierarchy_api_raw import HierarchyApiRaw


class HierarchyApi(
    GetList,
    GetNodeById,
    GetPathById,
):
    """NOTE:
    This class is auto generated by Konfig (https://konfigthis.com)
    """
    raw: HierarchyApiRaw

    def __init__(self, api_client=None):
        super().__init__(api_client)
        self.raw = HierarchyApiRaw(api_client)
