# coding: utf-8

"""
    HR API

    <a href='swaggerv2.json'>Download Swagger Json in OAS2 Format.</a>

    The version of the OpenAPI document: 2
    Contact: hrapi@iris.co.uk
    Created by: https://help.iris.co.uk/hr/cascade/api/
"""

from iris_software_group_cascade_python_sdk.paths.hierarchy.get import GetListRaw
from iris_software_group_cascade_python_sdk.paths.hierarchy_id.get import GetNodeByIdRaw
from iris_software_group_cascade_python_sdk.paths.hierarchy_id_path.get import GetPathByIdRaw


class HierarchyApiRaw(
    GetListRaw,
    GetNodeByIdRaw,
    GetPathByIdRaw,
):
    """NOTE:
    This class is auto generated by Konfig (https://konfigthis.com)
    """
    pass
