# coding: utf-8

"""
    HR API

    <a href='swaggerv2.json'>Download Swagger Json in OAS2 Format.</a>

    The version of the OpenAPI document: 2
    Contact: hrapi@iris.co.uk
    Created by: https://help.iris.co.uk/hr/cascade/api/
"""

from iris_software_group_cascade_python_sdk.paths.jobs.post import CreateNewJob
from iris_software_group_cascade_python_sdk.paths.jobs_id.get import GetById
from iris_software_group_cascade_python_sdk.paths.jobs.get import GetList
from iris_software_group_cascade_python_sdk.paths.jobs_id.put import UpdateById
from iris_software_group_cascade_python_sdk.apis.tags.jobs_api_raw import JobsApiRaw


class JobsApi(
    CreateNewJob,
    GetById,
    GetList,
    UpdateById,
):
    """NOTE:
    This class is auto generated by Konfig (https://konfigthis.com)
    """
    raw: JobsApiRaw

    def __init__(self, api_client=None):
        super().__init__(api_client)
        self.raw = JobsApiRaw(api_client)
