# coding: utf-8

"""
    HR API

    <a href='swaggerv2.json'>Download Swagger Json in OAS2 Format.</a>

    The version of the OpenAPI document: 2
    Contact: hrapi@iris.co.uk
    Created by: https://help.iris.co.uk/hr/cascade/api/
"""

from iris_software_group_cascade_python_sdk.paths.publicholidays_id.get import GetLocationListById
from iris_software_group_cascade_python_sdk.paths.publicholidays.get import GetLocations
from iris_software_group_cascade_python_sdk.apis.tags.public_holidays_api_raw import PublicHolidaysApiRaw


class PublicHolidaysApi(
    GetLocationListById,
    GetLocations,
):
    """NOTE:
    This class is auto generated by Konfig (https://konfigthis.com)
    """
    raw: PublicHolidaysApiRaw

    def __init__(self, api_client=None):
        super().__init__(api_client)
        self.raw = PublicHolidaysApiRaw(api_client)
