# coding: utf-8

"""
    HR API

    <a href='swaggerv2.json'>Download Swagger Json in OAS2 Format.</a>

    The version of the OpenAPI document: 2
    Contact: hrapi@iris.co.uk
    Created by: https://help.iris.co.uk/hr/cascade/api/
"""

from iris_software_group_cascade_python_sdk.paths.publicholidays_id.get import GetLocationListByIdRaw
from iris_software_group_cascade_python_sdk.paths.publicholidays.get import GetLocationsRaw


class PublicHolidaysApiRaw(
    GetLocationListByIdRaw,
    GetLocationsRaw,
):
    """NOTE:
    This class is auto generated by Konfig (https://konfigthis.com)
    """
    pass
